---
title: "QC_Resistance_correlation"
author: "Geoffrey Olweny"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readr)
library(ggpubr)
library(janitor)
```

```{r}
arg <- read_csv("cleaned_resistance_data.csv") %>%
  clean_names()

vir <- read_csv("cleaned_virulence_data.csv") %>%
  clean_names()

qc <- read_csv("Supplementary_Table_Assembly_QC.csv") %>%
  clean_names()
```

```{r}
arg_counts <- arg %>%
  distinct(sample_id, gene) %>%
  count(sample_id, name = "arg_count")

head(arg_counts)
```

```{r}
vf_counts <- vir %>%
  distinct(sample_id, gene) %>%
  count(sample_id, name = "vf_count")

head(vf_counts)
```
```{r}
qc_analysis <- qc %>%
  left_join(arg_counts, by = "sample_id") %>%
  left_join(vf_counts, by = "sample_id")

glimpse(qc_analysis)
```
```{r}
summary(is.na(qc_analysis))
```
```{r}
cor.test(
  qc_analysis$contig_count,
  qc_analysis$arg_count,
  method = "spearman"
)
```

```{r}
cor.test(
  qc_analysis$n50,
  qc_analysis$arg_count,
  method = "spearman"
)
```
```{r}
cor.test(
  qc_analysis$genome_size_bp,
  qc_analysis$arg_count,
  method = "spearman"
)
```

```{r}
cor.test(
  qc_analysis$contig_count,
  qc_analysis$vf_count,
  method = "spearman"
)
```

```{r}
p1 <- ggplot(qc_analysis,
             aes(x = contig_count,
                 y = arg_count)) +
  geom_point(size = 2.5,
             alpha = 0.7,
             color = "#2C7FB8") +
  geom_smooth(method = "lm",
              se = TRUE,
              color = "black") +
  stat_cor(method = "spearman") +
  theme_classic(base_size = 14) +
  labs(
    x = "Contig count",
    y = "ARG count"
  )

p1
```

```{r}
p2 <- ggplot(qc_analysis,
             aes(x = n50,
                 y = arg_count)) +
  geom_point(size = 2.5,
             alpha = 0.7,
             color = "#D95F0E") +
  geom_smooth(method = "lm",
              se = TRUE,
              color = "black") +
  stat_cor(method = "spearman") +
  theme_classic(base_size = 14) +
  labs(    x = "N50",
    y = "ARG count"
  )

p2
```

```{r}
p3 <- ggplot(qc_analysis,
             aes(x = genome_size_bp,
                 y = arg_count)) +
  geom_point(size = 2.5,
             alpha = 0.7,
             color = "#31A354") +
  geom_smooth(method = "lm",
              se = TRUE,
              color = "black") +
  stat_cor(method = "spearman") +
  theme_classic(base_size = 14) +
  labs(    x = "Genome size (bp)",
    y = "ARG count"
  )

p3
```

```{r}
p4 <- ggplot(qc_analysis,
             aes(x = contig_count,
                 y = vf_count)) +
  geom_point(size = 2.5,
             alpha = 0.7,
             color = "#756BB1") +
  geom_smooth(method = "lm",
              se = TRUE,
              color = "black") +
  stat_cor(method = "spearman") +
  theme_classic(base_size = 14) +
  labs(    x = "Contig count",
    y = "Virulence gene count"
  )

p4
```

```{r}
library(patchwork)

combined_qc_figure <-
  (p1 + p2) /
  (p3 + p4) +
  plot_annotation(
    tag_levels = "A"
  )

combined_qc_figure
ggsave(
  "Figure_SX_Assembly_QC_vs_Gene_Burden.png",
  combined_qc_figure,
  width = 14,
  height = 12,
  dpi = 1200
)

ggsave(
  "Figure_SX_Assembly_QC_vs_Gene_Burden.pdf",
  combined_qc_figure,
  width = 14,
  height = 12
)

p1 <- p1 + theme(
  plot.title = element_text(face = "bold"),
  axis.title = element_text(face = "bold")
)

p2 <- p2 + theme(
  plot.title = element_text(face = "bold"),
  axis.title = element_text(face = "bold")
)

p3 <- p3 + theme(
  plot.title = element_text(face = "bold"),
  axis.title = element_text(face = "bold")
)

p4 <- p4 + theme(
  plot.title = element_text(face = "bold"),
  axis.title = element_text(face = "bold")
)

```

